# Generated by Django 6.1.1 on 2026-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xat',
            name='template',
            field=models.CharField(choices=[('rad', 'Rad etish'), ('tasdiqlandi', 'Tasdiqlash'), ('tayinlandi', 'Tayinlash'), ('muddat', "Muddat so'rash"), ('arizaKiritilgan', 'Ariza kiritilgan')], max_length=32),
        ),
    ]
