# Generated by Django 5.2.6 on 2026-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0004_hisob_raqami_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='xat',
            name='tuman',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tuman'),
        ),
    ]
