# Generated by Django 5.2.6 on 2026-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0005_xat_tuman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xat',
            name='template',
            field=models.CharField(choices=[('rad', 'Rad etish'), ('tasdiqlandi', 'Tasdiqlash'), ('tayinlandi', 'Tayinlash'), ('muddat', "Muddat so'rash"), ('arizaKiritilgan', 'Ariza kiritilgan'), ('arizaKiritilmagan', 'Ariza kiritilmagan')], max_length=32),
        ),
    ]
