# Generated by Django 5.2.6 on 2026-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0006_ariza_kiritilmagan_shabloni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xat',
            name='template',
            field=models.CharField(choices=[('rad', 'Rad etish'), ('toxtatilgan', "To'lov to'xtatilgan"), ('tasdiqlandi', 'Tasdiqlash'), ('tayinlandi', 'Tayinlash'), ('muddat', "Muddat so'rash"), ('arizaKiritilgan', 'Ariza kiritilgan'), ('arizaKiritilmagan', 'Ariza kiritilmagan')], max_length=32),
        ),
    ]
