# Generated by Django 6.1.1 on 2026-09-11 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriya', models.CharField(choices=[('oziq_ovqat', 'Oziq-ovqat'), ('kiyim_kechak', 'Kiyim-kechak'), ('kommunal_tolovlar', "Kommunal to'lovlar"), ('uy_joy', "Uy-joy ta'mirlash"), ('favqulodda', 'Favqulodda (shoshilinch) yordam')], max_length=32)),
                ('holat', models.CharField(choices=[('tayinlangan', 'Tayinlangan (ijobiy)'), ('rad', 'Rad etilgan')], max_length=16)),
                ('mfy', models.CharField(max_length=255, verbose_name='MFY')),
                ('kucha', models.CharField(max_length=255, verbose_name="Ko'cha")),
                ('fio', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('tashkilot', models.CharField(max_length=255, verbose_name='Murojaat tashkiloti')),
                ('sana', models.DateField(verbose_name='Murojaat sanasi')),
                ('murojaat_raqami', models.CharField(max_length=100, verbose_name='Murojaat raqami')),
                ('ariza_raqami', models.CharField(max_length=100, verbose_name='Ariza raqami')),
                ('ajratilgan_summa', models.CharField(blank=True, default='', max_length=100, verbose_name="Ajratilgan summa (so'm)")),
                ('rad_sabab_kodlari', models.JSONField(blank=True, default=list, verbose_name='Rad sabablari (kodlar)')),
                ('boshqa_sabab_matni', models.TextField(blank=True, default='', verbose_name='Boshqa sabab matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arizalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
