# Generated by Django 6.1.1 on 2026-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ariza_tuman_xodimprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimprofil',
            name='rol',
            field=models.CharField(choices=[('saxovat', "Saxovat va ko'mak (arizalar)"), ('xat', 'Xat tizimi')], default='saxovat', max_length=16, verbose_name='Rol'),
        ),
    ]
