# Generated by Django 6.1.1 on 2026-09-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_xodimprofil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('rahbar', models.CharField(blank=True, default='', max_length=255, verbose_name='Rahbar F.I.O')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
            },
        ),
        migrations.AddField(
            model_name='xodimprofil',
            name='tashkilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xodimlar', to='core.tashkilot', verbose_name='Tashkilot'),
        ),
    ]
