# Generated by Django 5.2.6 on 2026-09-12 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rol_va_kategoriya_yangilash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XizmatHujjati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('bildirgi', 'Bildirgi (intizom yuzasidan)'), ('ogohlantirish', "Ogohlantirish xati (zoom yig'ilishi)"), ('talabnoma', 'Talabnoma (boshqa tashkilotga)')], max_length=20, verbose_name='Hujjat turi')),
                ('mahalla', models.CharField(max_length=255, verbose_name='Mahalla / MFY nomi')),
                ('xodim_fio', models.CharField(max_length=255, verbose_name='Ijtimoiy xodim F.I.O')),
                ('ish_boshlagan_sana', models.DateField(blank=True, null=True, verbose_name='Lavozimga kirgan sana')),
                ('buzilish_sanasi', models.CharField(blank=True, default='', help_text='Masalan: 2026-yilning 19-20-avgust', max_length=100, verbose_name='Qoidabuzarlik sanasi')),
                ('ish_vaqti', models.CharField(blank=True, default='09:00', max_length=20, verbose_name='Ish boshlanish vaqti')),
                ('yigilish_sanasi', models.CharField(blank=True, default='', help_text='Masalan: 30-iyun', max_length=100, verbose_name="Yig'ilish sanasi")),
                ('rahbar_lavozimi', models.CharField(blank=True, default='', max_length=255, verbose_name="Yig'ilishni o'tkazgan rahbar lavozimi")),
                ('rahbar_fio', models.CharField(blank=True, default='', max_length=255, verbose_name="Yig'ilishni o'tkazgan rahbar F.I.O")),
                ('qabul_qiluvchi', models.CharField(blank=True, default='', help_text='"...boshlig\'iga" so\'zisiz. Masalan: Andijon tuman kambag\'allikni qisqartirish va bandlik bo\'limi', max_length=500, verbose_name='Qaysi tashkilotga')),
                ('fuqaro_fio', models.CharField(blank=True, default='', max_length=255, verbose_name='Fuqaro F.I.O')),
                ('fuqaro_tugilgan_sana', models.DateField(blank=True, null=True, verbose_name="Fuqaro tug'ilgan sana")),
                ('yordam_turi', models.CharField(blank=True, default='', max_length=500, verbose_name="So'ralayotgan yordam turi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xizmat_hujjatlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xizmat hujjati',
                'verbose_name_plural': 'Xizmat hujjatlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='xizmat_muallif_sana_idx'), models.Index(fields=['turi'], name='xizmat_turi_idx')],
            },
        ),
    ]
