# Generated by Django 6.1.1 on 2026-09-11 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('rad', 'Rad etish'), ('tasdiqlandi', 'Tasdiqlash'), ('tayinlandi', 'Tayinlash'), ('muddat', "Muddat so'rash"), ('arizaKiritilmagan', 'Ariza kiritilmagan'), ('arizaKiritilgan', 'Ariza kiritilgan')], max_length=32)),
                ('fio', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('mfy_nomi', models.CharField(max_length=255, verbose_name='MFY nomi')),
                ('street', models.CharField(max_length=255, verbose_name="Ko'cha nomi")),
                ('murojaatfrom', models.CharField(max_length=500, verbose_name='Qayerdan murojaat')),
                ('murojaat_raqami', models.CharField(max_length=100, verbose_name='Murojaat raqami')),
                ('murojaat_vaqti', models.DateField(verbose_name='Murojaat sanasi')),
                ('ariza_maqsadi', models.CharField(blank=True, default='', max_length=255, verbose_name='Ariza maqsadi')),
                ('ariza_vaqti', models.DateField(blank=True, null=True, verbose_name='Ariza sanasi')),
                ('ariza_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Ariza raqami (ID)')),
                ('is_qayta', models.BooleanField(default=False, verbose_name="Qayta o'rganildimi")),
                ('rad_sabablari', models.JSONField(blank=True, default=dict, verbose_name='Rad sabablari')),
                ('tasdiq_sanasi', models.CharField(blank=True, default='', max_length=100, verbose_name='Tasdiqlash sanasi')),
                ('tolov_sanasi', models.CharField(blank=True, default='', max_length=100, verbose_name="To'lov sanasi")),
                ('tolov_sum', models.CharField(blank=True, default='', max_length=100, verbose_name="To'lov summasi")),
                ('xsobraqam', models.CharField(blank=True, default='', max_length=100, verbose_name='Hisob raqami')),
                ('tayinlash_qoshimcha', models.CharField(blank=True, default='', max_length=1000, verbose_name="Qo'shimcha ma'lumot")),
                ('qoshimcha_malumot', models.CharField(blank=True, default='', max_length=1000, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xat',
                'verbose_name_plural': 'Xatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
